# Kubernetes Deployment for Heimnetz Production Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimnetz-production
  namespace: heimnetz
  labels:
    app: heimnetz-production
    version: v11.0
    component: web-server
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: heimnetz-production
  template:
    metadata:
      labels:
        app: heimnetz-production
        version: v11.0
        component: web-server
    spec:
      containers:
      - name: heimnetz-production
        image: heimnetz/production:v11.0
        ports:
        - containerPort: 5004
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: FLASK_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DATABASE_URL
          value: "sqlite:///data/heimnetz.db"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: heimnetz-secrets
              key: secret-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: heimnetz-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5004
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: config-volume
          mountPath: /config
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: heimnetz-data-pvc
      - name: config-volume
        configMap:
          name: heimnetz-config
      imagePullSecrets:
      - name: registry-secret
---
# Service for Heimnetz Production Server
apiVersion: v1
kind: Service
metadata:
  name: heimnetz-production-service
  namespace: heimnetz
  labels:
    app: heimnetz-production
    component: web-server
spec:
  selector:
    app: heimnetz-production
  ports:
  - name: http
    port: 80
    targetPort: 5004
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: heimnetz-production-hpa
  namespace: heimnetz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heimnetz-production
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: heimnetz-production-pdb
  namespace: heimnetz
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: heimnetz-production
